### ISSUE TITLE
Issues with TS/JS imports

### ISSUE THREAD

**Issue by GantMan** [orta/danger-plugin-spellcheck#11]
👋  Hiya

First time with Danger JS, been working with it today.

Found 2 issues, which I have solutions for, they both might return to master as PRs, but I'm apparently stumped with my latest issue.

### Empty Dangerfile does a simple import 
```js
import { schedule } from 'danger'
// import spellcheck from 'danger-plugin-spellcheck'

// let's spellcheck
// schedule(spellcheck())
```
![image](https://user-images.githubusercontent.com/997157/34328703-c48a336e-e8ab-11e7-84a7-e9b00701b1da.png)
YAY! 🎉 

### Uncomment import for spellcheck now
```js
import { schedule } from 'danger'
import spellcheck from 'danger-plugin-spellcheck'

// let's spellcheck
// schedule(spellcheck())
```
![image](https://user-images.githubusercontent.com/997157/34328714-f3dcd004-e8ab-11e7-9bc7-98f8a70b8fff.png)
❌  Failing import

Unexpected token import???   But but... we import on line 1 just fine.
If I switch this to a `require` it will work, but the resulting const will not be a function.

What am I doing wrong?

**Comment by GantMan** [comment]
## UPDATE

My project is a TS project, but I was using JS for my dangerfile due to a bug.  I'll be fixing the bug, and that will likely fix this issue... but it doesn't change the fact that I was completely lost on what just happened.

**Comment by GantMan** [comment]
https://github.com/danger/danger-js/pull/456

**Comment by orta** [comment]
I'm willing to bet that because you were using TS, babel wasn't in your dep tree - so you couldn't use `import`/`export` as there was nothing to transpire with. I wonder if I can improve the messaging in Danger about this.

**Comment by orta** [comment]
The danger import is fake (it's removed at runtime)

**Comment by GantMan** [comment]
Ah I saw that!  It just didn't click.  

Excellent, that restores sanity for me :)
