### ISSUE TITLE
Allow spellcheck properties via spellcheck command

### ISSUE THREAD

**Issue by GantMan** [orta/danger-plugin-spellcheck#13]
Having a JSON file for the spellcheck is cool.  Ideally, I would like to be able to append settings from my dangerfile.js so I could add ignore words from various places.  I already have a spellchecked list of words for my editor, and it would be great to include that.

## I'd be willing to take on this PR.   
What's needed, is that we'd be able to add ignore and whitelist to the options of the spellcheck function.  These would be merged by the spellcheck.  Would you accept something like this?

**Comment by orta** [comment]
Yep, that's totally 👍 with me - expand this interface

https://github.com/orta/danger-plugin-spellcheck/blob/decba28b74cc1c2c51ba31a5c880e6e9820ce8e7/src/index.ts#L29-L31

to something like:

```ts
export interface SpellCheckOptions {
  settings: string
  ignore?: string[]
  whitelistFiles?: string[]
}
```

Then have this function take those options into account 

https://github.com/orta/danger-plugin-spellcheck/blob/decba28b74cc1c2c51ba31a5c880e6e9820ce8e7/src/index.ts#L117-L135

**Comment by orta** [comment]
Shipped
