### ISSUE TITLE
Spellcheck only running on certain files

### ISSUE THREAD

**Issue by bj-mcduck** [orta/danger-plugin-spellcheck#24]
I've got danger and danger-plugin-spellcheck running through CircleCI and it is now able to post comments when there are errors in the `README.md`.

It doesn't seem to be analyzing anything in my `openapi.yml` file though, which is the main file I want checked.

I noticed there's a `whitelistFiles` option, but that's to _ignore_ certain files.
What can you do to specifically **add** a file to be evaluated?
Do you support yaml files?

**Comment by orta** [comment]
The code spell checker takes a arbitrary glob, should cover yml files: https://github.com/orta/danger-plugin-spellcheck#checking-code
