### ISSUE TITLE
Add an implicit per-project spell check settings

### ISSUE THREAD

**Issue by orta** [orta/danger-plugin-spellcheck#4]
This needs to be thought of from the perspective of Peril. 

Peril for Artsy runs [spellcheck](https://github.com/artsy/artsy-danger/blob/997d4fb7f4680973ac016eb75474ad15bf18c183/org/all-prs.ts#L7-L9) on [every repo](https://github.com/artsy/artsy-danger/blob/997d4fb7f4680973ac016eb75474ad15bf18c183/peril.settings.json#L6). So there is a global settings file for [all spellchecking](https://github.com/artsy/artsy-danger/blob/997d4fb7f4680973ac016eb75474ad15bf18c183/spellcheck.json) referenced at launch.

Ideally we want to be able to merge that settings object with a per-repo object. So here's how I could imagine it to work:

* Today this plugin [downloads the global settings](https://github.com/orta/danger-plugin-spellcheck/blob/6df8b8445df61670f4d0aa0f20086799544073ac/src/index.ts#L117-L1320) and merges them into the settings 

* Straight after this, there is a check for a file called `spellcheck.json` inside the repo (on the right branch) ( `const perRepoContents = await getFileContents("spellcheck.json", getPRParams(file))` )

* These changes are then merged in with the existing settings - giving the change to add new `whitelistedMarkdowns`  files, and new words to the `ignoredWords` section

**Comment by orta** [comment]
Ideally this can be used to also run without that settings string, you could just include `spellcheck.json` in your repo and it would be picked up when just using Danger

**Comment by jonallured** [comment]
I'm super into this idea, but I'm having a hard time parsing the code linked to - happy to pair on it though!

**Comment by orta** [comment]
Fixed by #7
